-- Passwordless admin authentication for issue #243.
-- Keeps ACCOUNT/TNMUser as the user source of truth for future user-management UI (#246).

ALTER TABLE ACCOUNT
    ADD COLUMN IF NOT EXISTS EMAIL_NORMALIZED VARCHAR(255) NULL AFTER EMAIL,
    ADD COLUMN IF NOT EXISTS LAST_LOGIN_AT DATETIME NULL AFTER ENABLED,
    ADD COLUMN IF NOT EXISTS LAST_LOGIN_METHOD VARCHAR(32) NULL AFTER LAST_LOGIN_AT,
    ADD COLUMN IF NOT EXISTS INVITED_AT DATETIME NULL AFTER LAST_LOGIN_METHOD,
    ADD COLUMN IF NOT EXISTS INVITE_ACCEPTED_AT DATETIME NULL AFTER INVITED_AT,
    ADD COLUMN IF NOT EXISTS AUTH_MIGRATION_REQUIRED BOOLEAN NOT NULL DEFAULT TRUE AFTER INVITE_ACCEPTED_AT;

UPDATE ACCOUNT
SET EMAIL_NORMALIZED = LOWER(TRIM(EMAIL))
WHERE EMAIL IS NOT NULL
  AND (EMAIL_NORMALIZED IS NULL OR EMAIL_NORMALIZED = '');

CREATE INDEX IF NOT EXISTS IDX_ACCOUNT_EMAIL_NORMALIZED
    ON ACCOUNT (EMAIL_NORMALIZED);

CREATE INDEX IF NOT EXISTS IDX_ACCOUNT_AUTH_MIGRATION_REQUIRED
    ON ACCOUNT (AUTH_MIGRATION_REQUIRED);

CREATE TABLE IF NOT EXISTS MAGIC_LINK_TOKEN (
    ID VARCHAR(64) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(64) NULL,
    TOKEN_HASH CHAR(64) NOT NULL UNIQUE,
    PURPOSE VARCHAR(32) NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    USED_AT DATETIME NULL,
    REQUESTED_EMAIL_HASH CHAR(64) NULL,
    REQUEST_IP_HASH CHAR(64) NULL,
    CREATED_AT DATETIME NOT NULL,
    CREATED_BY_ACCOUNT_ID VARCHAR(64) NULL,
    USER_AGENT VARCHAR(500) NULL,
    INDEX IDX_MAGIC_LINK_TOKEN_HASH (TOKEN_HASH),
    INDEX IDX_MAGIC_LINK_ACCOUNT_ID (ACCOUNT_ID),
    INDEX IDX_MAGIC_LINK_EXPIRES_AT (EXPIRES_AT)
);

CREATE TABLE IF NOT EXISTS user_credentials (
    credential_id VARBINARY(2048) PRIMARY KEY,
    user_entity_user_id VARCHAR(1000) NOT NULL,
    public_key BLOB NOT NULL,
    signature_count BIGINT NULL,
    uv_initialized BOOLEAN NULL,
    backup_eligible BOOLEAN NOT NULL,
    authenticator_transports VARCHAR(1000) NULL,
    public_key_credential_type VARCHAR(100) NOT NULL,
    backup_state BOOLEAN NOT NULL,
    attestation_object BLOB NULL,
    attestation_client_data_json BLOB NULL,
    created TIMESTAMP NULL,
    last_used TIMESTAMP NULL,
    label VARCHAR(1000) NOT NULL
);
