-- Weekly minyan review email preference for issue #34.
-- Existing and new accounts are opted in by default.

ALTER TABLE ACCOUNT
    ADD COLUMN IF NOT EXISTS WEEKLY_MINYAN_REVIEW_EMAILS_ENABLED BOOLEAN NOT NULL DEFAULT TRUE
        AFTER AUTH_MIGRATION_REQUIRED;

UPDATE ACCOUNT
SET WEEKLY_MINYAN_REVIEW_EMAILS_ENABLED = TRUE
WHERE WEEKLY_MINYAN_REVIEW_EMAILS_ENABLED IS NULL;
