package com.tbdev.teaneckminyanim.api;

import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * Serves the Scalar API reference UI at /api/docs.
 *
 * Scalar is a modern, open-source API documentation UI that renders an OpenAPI
 * spec into a clean, interactive reference. It is loaded entirely from CDN —
 * no extra Maven dependency is needed.
 *
 * The OpenAPI spec is generated by springdoc at /api/docs.json.
 */
@Controller
public class ScalarDocsController {

    @GetMapping(value = "/api/docs", produces = MediaType.TEXT_HTML_VALUE)
    @ResponseBody
    public ResponseEntity<String> scalarDocs() {
        String html = """
                <!doctype html>
                <html lang="en">
                  <head>
                    <title>Teaneck Minyanim — API Reference</title>
                    <meta charset="utf-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" type="image/svg+xml" href="/assets/icons/favicon.svg" />
                    <link rel="icon" type="image/png" href="/assets/icons/favicon.png" />
                  </head>
                  <body>
                    <script
                      id="api-reference"
                      data-url="/api/docs.json"
                      data-configuration='{
                        "theme": "kepler",
                        "layout": "modern",
                        "defaultOpenAllTags": true,
                        "metaData": {
                          "title": "Teaneck Minyanim — API Reference",
                          "description": "Public REST API for minyan schedules, zmanim, and announcements"
                        }
                      }'
                    ></script>
                    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
                  </body>
                </html>
                """;
        return ResponseEntity.ok()
                .contentType(MediaType.TEXT_HTML)
                .body(html);
    }
}
